apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: log4javasample
spec:
  template:
    spec:
      containers:
        - image: gcr.io/prepro-273413/log4java:latest2
          ports:
            - name: http1
              containerPort: 80