apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: log4shellcloudmss
spec:
  template:
    spec:
      containers:
        - image: europe-southwest1-docker.pkg.dev/banded-coder-401610/cloudmss/log4java:latest
          ports:
            - name: http1
              containerPort: 80